module vga_driver (
    input wire clk,

    output reg[3:0] R,
    output reg[3:0] G,
    output reg[3:0] B,
    output reg HS = 1'b1,
    output reg VS = 1'b1
);
    wire pllClk;
    wire pllLock;

    pll pll_instance(
        .clock_in(clk),
        .clock_out(pllClk),
        .locked(pllLock)
    );

    localparam HTOTAL = 800;
    localparam HACTIVE = 640;
    localparam HBLANK = 144;
    localparam HFPORCH = 8;
    localparam HSYNC = 96;
    localparam HBPORCH = 48;

    localparam VTOTAL = 525;
    localparam VACTIVE = 480;
    localparam VBLANK = 29;
    localparam VFPORCH = 2;
    localparam VSYNC = 2;
    localparam VBPORCH = 25;

    reg[10:0] hCounter = 0;
    reg[10:0] vCounter = 0;
    wire dataEnable;

    assign dataEnable = (hCounter < HACTIVE) && (vCounter < VACTIVE);

    always @(posedge pllClk) begin
        if(pllLock == 1) begin
            if(dataEnable) begin
                if(hCounter < 320) begin
                    if(vCounter < 240) begin
                        R <= 4'b1111;
                        G <= 4'b0000;
                        B <= 4'b0000;
                    end else begin
                        R <= 4'b0000;
                        G <= 4'b1111;
                        B <= 4'b0000;
                    end
                end else begin
                    if(vCounter < 240) begin
                        R <= 4'b0000;
                        G <= 4'b0000;
                        B <= 4'b1111;
                    end else begin
                        R <= 4'b0000;
                        G <= 4'b1111;
                        B <= 4'b1111;
                    end
                end
            end else begin
                        R <= 4'b0000;
                        G <= 4'b0000;
                        B <= 4'b0000;
            end

            if(hCounter >= HTOTAL-HSYNC-HBPORCH && hCounter < HTOTAL-HBPORCH) HS <= 0;
            else HS <= 1;

            if(vCounter >= VTOTAL-VSYNC-VBPORCH && vCounter < VTOTAL-VBPORCH) VS <= 0;
            else VS <= 1;

            if(hCounter == HTOTAL-1) begin
                hCounter <= 0;
                if(vCounter == VTOTAL-1) begin
                    vCounter <= 0;
                end else begin
                    vCounter <= vCounter + 1;
                end
            end else hCounter <= hCounter + 1;
        end
    end
endmodule

/*
25 Mhz clock - config values generated by running: icepll -i 12 -o 25.175

F_PLLIN:    12.000 MHz (given)
F_PLLOUT:   25.175 MHz (requested)
F_PLLOUT:   25.125 MHz (achieved)

FEEDBACK: SIMPLE
F_PFD:   12.000 MHz
F_VCO:  804.000 MHz

DIVR:  0 (4'b0000)
DIVF: 66 (7'b1000010)
DIVQ:  5 (3'b101)

FILTER_RANGE: 1 (3'b001)
*/
module pll(
	input  clock_in,
	output clock_out,
	output locked
	);

SB_PLL40_PAD #(
		.FEEDBACK_PATH("SIMPLE"),
		.DIVR(4'b0000),		    // DIVR =  0
		.DIVF(7'b1000010),	    // DIVF = 66
		.DIVQ(3'b101),		    // DIVQ =  5
		.FILTER_RANGE(3'b001)   // FILTER_RANGE = 1
	) uut (
		.LOCK(locked),
		.RESETB(1'b1),
		.BYPASS(1'b0),
		.PACKAGEPIN(clock_in),
		.PLLOUTCORE(clock_out)
		);

endmodule
